apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: app-container
          image: cato16/py-to-do:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"